# -*- coding: utf-8 -*-
"""Wine Quality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WMI54DkKDzjQ73pvZdIocTG3Lis3Gu8L

DATA PREPROCESSING
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/WINE QUALITY DATASET 1.zip')
df.head()

df.tail()

df.describe()

df.size

df.shape

df.columns

df.isnull().sum()

df.info()

df.dtypes

df.drop_duplicates(inplace= True)

df.describe()

"""DATA VISUALIZATION

HISTOGRAM
"""

sns.histplot(df['quality'],kde=True)
plt.title('Distribution of Wine Quality')
plt.xlabel('Quality')
plt.ylabel('Frequency')
plt.show()



"""BOX PLOT"""

sns.boxplot(x=df['quality'])
plt.title('Box Plot of Wine Quality')
plt.xlabel('quality')
plt.ylabel('density')
plt.show()

sns.boxplot(x=df['quality'])
plt.title('How ph is affecting quality')
plt.xlabel('quality')
plt.ylabel('ph')
plt.show()

sns.boxplot(x=df['quality'])
plt.title('How alcohol is affecting quality')
plt.xlabel('quality')
plt.ylabel('alcohol')
plt.show()



"""VIOLIN PLOT"""

sns.violinplot(x=df['quality'])
plt.title('Violin Plot of Wine Quality')
plt.xlabel('quality')
plt.ylabel('density')
plt.show()

sns.violinplot(x=df['quality'])
plt.title('How ph is affecting quality')
plt.xlabel('quality')
plt.ylabel('ph')
plt.show()

sns.violinplot(x=df['quality'])
plt.title('How alcohol is affecting quality')
plt.xlabel('quality')
plt.ylabel('alcohol')
plt.show()



"""COUNT PLOT"""

sns.countplot(x=df['quality'])
plt.title('Count Plot of Wine Quality')
plt.xlabel('quality')
plt.ylabel('Count')
plt.show()

sns.countplot(x=df['quality'])
plt.title('How ph is affecting quality')
plt.xlabel('quality')
plt.ylabel('ph')
plt.show()



"""CORRELATION MATRIX-heatmap"""

plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix Heatmap')
plt.show()

plt.figure(figsize=(10, 8))
plt.pie(df['quality'].value_counts(), labels=df['quality'].unique(), autopct='%1.1f%%')
plt.title('Distribution of Wine Quality')
plt.show()

